### ISSUE TITLE
Support for iframe embedding

### ISSUE THREAD

**Issue by wliao229** [ziolko/roombelt#10]
I use Organizr (https://organizr.app) to bookmark all services run on my private server. It uses iFrame to embed different web portals, and it would be nice if the roombelt admin page can be embedded too. Currently, it returns "Refused to display 'http://xxxx:3000/admin' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'." xxxx is the domain name.

**Comment by ziolko** [comment]
Thank you for this request. What about an environment variable `ALLOW_IN_IFRAME`? If this variable is set to true this header won't be send.

I don't want to disable `X-Frame-Options` by default, because it is an important security countermeasure.

**Comment by wliao229** [comment]
Thank you for the responses!

I am not an expert, but if that would allow the admin page be embedded, then that would be great!

On Jan 8, 2019, at 11:11 AM, Mateusz Zieliński <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for this request. What about an environment variable ALLOW_IN_IFRAME? If this variable is set to true this header won't be send.

I don't want to disable X-Frame-Options by default, because it is an important security countermeasure.

**Comment by ziolko** [comment]
I added support for a environement variable `DISABLE_FRAME_GUARD` which you can set to `true` to disable `X-Frame-Options` header. Keep in mind this introduces a risk of clickjacking as documented at https://helmetjs.github.io/docs/frameguard.

You can define `DISABLE_FRAME_GUARD` in the same place you define e.g. `GOOGLE_CLIENT_ID` and `DATABASE_URL`.

Please let me know if you need further assistance,
Mateusz

**Comment by wliao229** [comment]
I use Docker. Should I update the docker image?

**Comment by ziolko** [comment]
Yes, you need to pull newest version with `docker pull ziolko/roombelt:latest`. 

Remember to create a backup of your database before running the new version. Roombelt 0.4 comes with new functionalities and database migration process will be run. This should go without issues but you definitely should have a backup ;)

**Comment by wliao229** [comment]
Thank you. It works now, except that the Google oauth2 process still won't proceed in iframe: Refused to display 'https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar%20profile&prompt=&response_type=code&client_id=' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

If I authenticate it in a separate browser window or tab, then the embedding works. Otherwise, there will be a spinning circle at the center of the page. 

I think this cannot be changed from Google -- is it possible to provide a link or button that opens a new window for authentication?

**Comment by ziolko** [comment]
Thanks for feedback. I'm gonna take a look at this over the weekend.

**Comment by ziolko** [comment]
@wliao229 Unfortunately I didn't make it work seamlessly. The best I can provide right now is support for middle click on the login screen - starting from Roombelt 0.4.1 middle click on "Log in to admin panel" opens a new tab instead of navigating the current one. With this improvement you can open the login screen in a new tab, sign in there and continue using Roombelt in the original tab. 

I understand that this is an inconvenience. Good news is that Roombelt keeps your session open so you won't need to do it often.

Mateusz

**Comment by wliao229** [comment]
Thank you Mateusz,

This is good enough for me!

Wang


On Jan 12, 2019, at 1:02 PM, Mateusz Zieliński <notifications@github.com<mailto:notifications@github.com>> wrote:


@wliao229<https://github.com/wliao229> Unfortunately I didn't make it work seamlessly. The best I can provide right now is support for middle click on the login screen - starting from Roombelt 0.4.1 middle click on "Log in to admin panel" opens a new tab instead of navigating the current one. With this improvement you can open the login screen in a new tab, sign in there and continue using Roombelt in the original tab.

I understand that this is an inconvenience. Good news is that Roombelt keeps your session open so you won't need to do it often.

Mateusz

**Comment by ziolko** [comment]
I am glad it works for you. In this case I will close this issue. 

In case of any other problems with Roombelt just let me know.
